Create README.es.md for Web Dev for Beginners
microsoft/Web-Dev-For-Beginners pull request #1027
Opened 2022-12-28 13:48 UTC by ericjhernandezj

Creation of the README.md in Spanish for Web Dev for Beginners.

2023-07-15 04:45 UTC, abrilurena requested changes
¡Muchisimas gracias por toda tu ayuda y tiempo, @ericjhernandezj! He hecho algunos comentarios, por favor, si tienes alguna pregunta no dudes en escribirme. Mil gracias! ✨

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +Con nuestra UI creada, es hora de centrar nuestra atención en el JavaScript que proporcionará la lógica. We're going to break this down into a handful of steps:
```suggestion
Con nuestra UI creada, es hora de centrar nuestra atención en el JavaScript que proporcionará la lógica. Vamos a compartirte los pasos:
```

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +> **NOTA:** Podemos recuperar los elementos cuando queramos en código usando `document.getElementById`. Debido al hecho de que nos referiremos a estos elementos de manera regular, evitaremos errores
```suggestion
> **NOTA:** Cuando queramos, podemos recuperar los elementos en código usando `document.getElementById`. Debido al hecho de que nos referiremos a estos elementos de manera regular, evitaremos errores tipográficos con cadenas literales mediante el uso de constantes. Los Frameworks como [Vue.js](https://vuejs.org/) o [React](https://reactjs.org/) pueden ayudarte a administrar mejor la centralización de su código.
```

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +[![Types of variables](https://img.youtube.com/vi/JNIXfGiDWM8/0.jpg)](https://youtube.com/watch?v=JNIXfGiDWM8 "Types of variables")
```suggestion
[![Tipo de variables](https://img.youtube.com/vi/JNIXfGiDWM8/0.jpg)](https://youtube.com/watch?v=JNIXfGiDWM8 "Types of variables")
```

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +> 🎥 Haga clic en la imagen de arriba para ver un video sobre las variables.
```suggestion
```

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +
```suggestion

> 🎥 Haz clic en la imagen inferior para ver un video sobre las variables.

```

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +¡Has llegado hasta el final! El último paso es asegurarnos de que nuestra aplicación funcione. ¡Dale un tiro! No se preocupe si hay errores; **todos los desarrolladores** tienen errores. Examine los
```suggestion
¡Has llegado hasta el final! El último paso es asegurarnos de que nuestra aplicación funcione. ¡Pruebalo! No te preocupes si hay errores; **todos los desarrolladores** cometen errores. Examina los mensajes y soluciona según sea necesario.
```

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +![Animation of the game in action](../../../4-typing-game/images/demo.gif)
```suggestion
![Animacion de un juego en acción](../../../4-typing-game/images/demo.gif)
```

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +- Muestra un cuadro de diálogo modal con el mensaje de éxito
```suggestion
- Muestra un cuadro de diálogo modal _(modal dialog box)_ con el mensaje de éxito
```

2023-07-15 04:45 UTC, abrilurena commented on 4-typing-game/typing-game/translations/README.es.md
> +[Crear un nuevo juego de teclado](assignment.es.md)
```suggestion
[Crear un nuevo juego de teclado](./assignment.es.md)
```

2023-07-17 17:58 UTC, abrilurena requested changes
¡Hola, @ericjhernandezj! Muchas gracias! acabo de revisar el ultimo cambio que hiciste, solo quedan pendiente los demás que te habia mencionado :D 


En cada comentario, solo tienes que hacer clic en "commit suggestion" para que los cambios se añadan, por favor ✨ 🙏 💕 mil gracias!

<img width="780" alt="image" src="https://github.com/microsoft/Web-Dev-For-Beginners/assets/107883174/41624f37-6f0e-4962-99b0-8a37824521b4">


Si tienes alguna pregunta, por favor, no dudes en escribirme :D

2023-11-15 01:02 UTC, abrilurena commented
¡Hola, @ericjhernandezj! Si tienes alguna pregunta, por favor no dudes en enviarme mensaje ✨ ♥️

2025-02-19 05:17 UTC, Vaishhhnavi77 commented
"Is this issue still open for contribution?"

2025-02-21 19:15 UTC, abrilurena commented
@Vaishhhnavi77 Hi! We still need help with other sections :D thank you!

2025-02-22 06:41 UTC, payems commented
***@***.***

On Tue, Feb 18, 2025 at 9:24 PM Vaishhnavi ***@***.***> wrote:

> "Is this issue still open for contribution?"
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
> [image: Vaishhhnavi77]*Vaishhhnavi77* left a comment
> (microsoft/Web-Dev-For-Beginners#1027)
>
> "Is this issue still open for contribution?"
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-06-12 01:11 UTC, closed without merging