Create danish README.md
microsoft/Web-Dev-For-Beginners pull request #1150
Opened 2023-06-29 19:38 UTC by ockley

Ups. I didn't see that it started a new patch. I am still trying my way around on GitHub. Hopefully, it gets better with routine :)

2023-06-30 07:57 UTC, IchaAngelina approved these changes

2023-06-30 07:58 UTC, IchaAngelina approved these changes

2023-11-05 09:57 UTC, kevinanielsen requested changes
I suggest a few changes but overall a great translation!

2023-11-05 09:57 UTC, kevinanielsen commented on 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.da.md
> +Denne lektion dækker det grundlæggende i programmeringssprog. De emner, der behandles her, gælder for de fleste moderne programmeringssprog i dag. I afsnittet 'Tools of the Trade' lærer du om nyttig
```suggestion
Denne lektion dækker det grundlæggende i programmeringssprog. De emner, der omtales her, gælder for de fleste moderne programmeringssprog i dag. I afsnittet 'Tools of the Trade' lærer du om nyttig software, der hjælper dig som udvikler.
```

2023-11-05 09:57 UTC, kevinanielsen commented on 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.da.md
> +![Intro Programming](/sketchnotes/webdev101-programming.png)
```suggestion
![Introduktion til Programmering](/sketchnotes/webdev101-programming.png)
```

2023-11-05 09:57 UTC, kevinanielsen commented on 1-getting-started-lessons/2-github-basics/translations/README.da.md
> +## Quiz for undervisning
```suggestion
## Quiz før undervisning
```

2023-11-05 09:57 UTC, kevinanielsen commented on 1-getting-started-lessons/2-github-basics/translations/README.da.md
> +`git config --list`
Remove duplicate text
```markdown
For at tjekke, om Git allerede er konfigureret, kan du skrive:
`git config --list`
```

2023-11-08 01:34 UTC, Sticknmove approved these changes

2025-08-15 06:01 UTC, closed without merging