Adding FR.fr
microsoft/Web-Dev-For-Beginners pull request #181
Opened 2021-02-05 21:54 UTC by yezz123

## Track translation progress by opening a draft PR using this template and checking off the translations completed

Each lesson includes a translation of the README.md and the Assignment.md file, if available. Only mark the lesson complete if both those files are translated per lesson, please.

- [X] 1
- [X] 1-1
- [X] translations

2021-02-06 15:42 UTC, jlooper commented
aha! bonjour!

2021-02-06 16:11 UTC, yezz123 commented
> aha! bonjour!

Bonjour! @jlooper

2021-02-08 21:52 UTC, jlooper reviewed
hi, do you want me to merge this? will you continue doing the other files? Merci!

2021-02-08 22:40 UTC, yezz123 commented
> hi, do you want me to merge this? will you continue doing the other files? Merci!

Bonsoir @jlooper !
You can merge it and when i finish the others i will create an other Pull request with the new Files.
Maybe also i will try to translate it to AR.ar (Arabic language).

2021-02-11 16:41 UTC, bl-ue requested changes
Hi! I don't know French, but I found some apparent mistakes.

2021-02-11 16:41 UTC, bl-ue commented on 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.fr.md
> +PLa programmation (également appelée codage) est le processus d'écriture d'instructions sur un appareil, tel qu'un ordinateur ou un appareil mobile. Nous écrivons ces instructions avec un langage de
```suggestion
Pla programmation (également appelée codage) est le processus d'écriture d'instructions sur un appareil, tel qu'un ordinateur ou un appareil mobile. Nous écrivons ces instructions avec un langage de programmation, qui est ensuite interprété par l'appareil. Ces ensembles d'instructions peuvent être désignés sous différents noms, mais *programme*, *programme informatique*, *application (application)* et *exécutable* sont quelques noms courants.
```

2021-02-11 16:41 UTC, bl-ue commented on 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.fr.md
> +* Les langues de bas niveau *nécessitent généralement moins d'étapes que les* langues de haut niveau * pour qu'un appareil interprète les instructions. Cependant, ce qui rend les langages de haut niv
```suggestion
*Les langues de bas niveau* nécessitent généralement moins d'étapes que les *langues de haut niveau* pour qu'un appareil interprète les instructions. Cependant, ce qui rend les langages de haut niveau populaires, c'est leur lisibilité et leur support. JavaScript est considéré comme un langage de haut niveau.
```

2021-02-11 16:41 UTC, bl-ue commented on 1-getting-started-lessons/1-intro-to-programming-languages/translations/README.fr.md
> +* Les langues de bas niveau *nécessitent généralement moins d'étapes que les* langues de haut niveau * pour qu'un appareil interprète les instructions. Cependant, ce qui rend les langages de haut niv
In this one it looks like the emphasis characters were pushed around...

2021-02-11 20:08 UTC, bl-ue approved these changes

2021-02-11 20:17 UTC, yezz123 commented
> Hi! I don't know French, but I found some apparent mistakes.

Thank you @bl-ue for your reviews i appreciate that 🥇

2021-03-19 15:13 UTC, jlooper commented
hi, can I get an idea of status here?

2021-03-19 15:38 UTC, yezz123 commented
> hi, can I get an idea of status here?

The status stay stable no updates just the same file 👍🏻

2021-03-19 16:17 UTC, jlooper commented
> > hi, can I get an idea of status here?
> 
> The status stay stable no updates just the same files 👍🏻

Thanks, I will wait until the task is complete, in this case, to avoid partial translations. thank you!

2021-03-23 18:37 UTC, manman1500 reviewed
0991615378

2021-03-23 18:39 UTC, manman1500 commented
0991615378

2021-03-24 08:11 UTC, manman1500 approved these changes
![Screenshot_2021-03-24-09-11-42-28.jpg](https://user-images.githubusercontent.com/81156960/112276278-243dda00-8cb3-11eb-9807-553104710a19.jpg)

2021-03-24 10:49 UTC, jishnugit commented
9567889784

2021-03-24 13:33 UTC, milliondollarbabe11 commented
thanks I am good

2021-03-24 13:41 UTC, bl-ue commented
@yezz123 this is done, right?  If so, @jlooper can we get it merged and then lock it to stop this odd spam?

2021-03-24 13:56 UTC, yezz123 commented
> @yezz123 this is done, right? If so, @jlooper can we get it merged and then lock it to stop this odd spam?

I guess its done but i will updates it anytime if i got time.
But for those file are good & clean translate 👍🏻

2021-03-24 15:41 UTC, jlooper commented
yes, the spam is EXTREMELY annoying @manman1500 and needs to stop

I'll merge these, thank you @yezz123

2021-03-24 15:42 UTC, merged