add Indonesian language
microsoft/Web-Dev-For-Beginners pull request #616
Opened 2022-02-28 08:17 UTC by GarudaID

2022-02-28 08:19 UTC, GarudaID commented
I added some Indonesian language in the Readme file

2022-03-01 01:25 UTC, jlooper requested changes

2022-03-01 01:25 UTC, jlooper commented on translations/README.id.md
> +[![Promo video](images/web.gif)](https://youtube.com/watch?v=R1wrdtmBSII "Promo video")
hi, the images will need relative links - ../../

2022-03-01 02:34 UTC, GarudaID commented
Fix project images links in README.md

2022-03-06 04:16 UTC, jlooper commented
hi, the links to the lessons need to be fixed (the ones in the table) - add '../' as necessary to avoid 404s

2022-03-09 13:51 UTC, jlooper requested changes

2022-03-09 13:51 UTC, jlooper commented on translations/README.id.md
> +[![Promo video](https://github.com/GarudaID/Web-Dev-For-Beginners/blob/main/images/web.gif)](https://youtube.com/watch?v=R1wrdtmBSII "Promo video")
Wrong link

2022-03-29 00:24 UTC, merged