translated to tamil language
microsoft/Web-Dev-For-Beginners pull request #623
Opened 2022-03-08 04:58 UTC by ndrohith09

Translated all lessons to tamil language

2022-03-08 14:24 UTC, jlooper commented
hi, thank you - the localized code for Tamil seems to be 'ta' so please rename the references to that in the files, thank you!

2022-03-08 14:26 UTC, jlooper requested changes
we don't need to change that as the file is named `.github`

2022-03-08 14:26 UTC, jlooper requested changes
let's change all references to Tamil to be 'ta'

2022-03-08 15:38 UTC, ndrohith09 commented on 3-terrarium/translations/README.tam.md
> +1. [ஹெச்டிஎம்எல் அறிமுகம்](../1-intro-to-html/translations/README.tam.md)
Yes , I will .Thank you!

2022-03-08 15:39 UTC, ndrohith09 commented
All changes which were requested were performed.Thank You!

2022-03-09 13:54 UTC, jlooper requested changes
Please roll back the edit to .github

2022-03-09 14:26 UTC, ndrohith09 commented
Status

- [X] 1
- [X] 2
- [X] 2
- [X] 3
- [X] 4
- [X] 5
- [X] 6
- [X] 7
- [X] Quiz

2022-03-09 14:40 UTC, ndrohith09 commented
> Please roll back the edit to .github

Are you asking about the checklist for translation?

2022-03-09 14:43 UTC, jlooper commented
> > Please roll back the edit to .github
> 
> Are you asking about the checklist for translation?

no, it's the edit you made to change the spelling of the folder name from `.github` to `github` in the original file

2022-03-09 14:56 UTC, ndrohith09 commented
> > > Please roll back the edit to .github
> > 
> > 
> > Are you asking about the checklist for translation?
> 
> no, it's the edit you made to change the spelling of the folder name from `.github` to `github` in the original file

Yes ! Sorry . I modified it. You can review now

2022-03-09 19:34 UTC, jlooper approved these changes

2022-03-09 19:34 UTC, merged