Add README translation (ES) for getting-started-lessons
microsoft/Web-Dev-For-Beginners pull request #779
Opened 2022-10-02 14:17 UTC by JCarlosR

- Add `README.es.md` translation for `1-getting-started-lessons`.
- Remove blank lines at the end of the `1-getting-started-lessons\README.md` file.

2022-10-02 14:18 UTC, JCarlosR commented
@microsoft-github-policy-service agree

2022-10-04 17:43 UTC, abrilurena requested changes
¡Hola, Carlos! Muchas gracias por tu ayuda y tiempo 👐 ♥️ Hice algunos comentarios, quedo al pendiente de si tienes alguna duda :)

2022-10-04 17:43 UTC, abrilurena commented on 1-getting-started-lessons/translations/README.es.md
> +En esta sección del plan de estudios, se le presentarán conceptos no basados en proyectos, importantes para convertirse en un desarrollador profesional.
```suggestion
En esta sección del plan de estudios, se te presentarán conceptos importantes para convertirte en un desarrollador profesional.
```

2022-10-04 17:43 UTC, abrilurena commented on 1-getting-started-lessons/translations/README.es.md
> +1. [Introducción a los lenguajes de programación y herramientas del oficio](1-intro-to-programming-languages/README.md)
```suggestion
1. [Introducción a los lenguajes de programación y herramientas del oficio](../1-intro-to-programming-languages/README.md)
```

2022-10-04 17:43 UTC, abrilurena commented on 1-getting-started-lessons/translations/README.es.md
> +2. [Introducción a GitHub](2-github-basics/README.md)
```suggestion
2. [Introducción a GitHub](../2-github-basics/README.md)
```

2022-10-04 17:43 UTC, abrilurena commented on 1-getting-started-lessons/translations/README.es.md
> +3. [Conceptos básicos de Accesibilidad](3-accessibility/README.md)
```suggestion
3. [Conceptos básicos de Accesibilidad](../3-accessibility/README.md)
```

2022-10-04 19:29 UTC, JCarlosR commented on 1-getting-started-lessons/translations/README.es.md
> +En esta sección del plan de estudios, se le presentarán conceptos no basados en proyectos, importantes para convertirse en un desarrollador profesional.
Gracias, estuve revisando otras traducciones al español y veo que también se escribe de esta manera. Ahora lo actualizo.

2022-10-04 19:30 UTC, JCarlosR commented on 1-getting-started-lessons/translations/README.es.md
> +3. [Conceptos básicos de Accesibilidad](3-accessibility/README.md)
He subido un nuevo commit. Por favor me dices si es necesario hacer rebase para juntar ambos commits en uno, o si está bien como está ahora.

2022-10-04 20:15 UTC, abrilurena approved these changes

2022-10-04 21:06 UTC, merged

2022-10-19 04:05 UTC, Sticknmove reviewed
Thanks

2022-10-19 04:06 UTC, Sticknmove reviewed
Thanks

2022-10-19 04:06 UTC, Sticknmove reviewed
Thanks

2022-10-19 04:07 UTC, Sticknmove reviewed
Thanks

2022-10-19 07:49 UTC, Sticknmove reviewed
Thanks

2022-10-19 07:50 UTC, Sticknmove reviewed
Thanks

2022-10-19 07:50 UTC, Sticknmove reviewed
Thanks

2022-10-19 07:50 UTC, Sticknmove reviewed
Thanks

2022-10-19 07:50 UTC, Sticknmove reviewed
Thanks

2022-10-19 07:51 UTC, Sticknmove reviewed
Thanks

2022-10-19 09:09 UTC, Sticknmove reviewed
Thanks

2022-10-19 09:09 UTC, Sticknmove reviewed
Thanks

2022-10-19 09:09 UTC, Sticknmove reviewed
Thanks

2022-10-19 09:10 UTC, Sticknmove reviewed
Thanks

2022-10-19 09:11 UTC, Sticknmove reviewed
Thanks

2022-10-19 10:09 UTC, Sticknmove commented
Thanks

2022-10-19 10:09 UTC, Sticknmove commented
Thanks

2022-10-19 10:09 UTC, Sticknmove commented
Thanks

2022-10-19 10:10 UTC, Sticknmove commented
Thanks

2022-10-19 10:10 UTC, Sticknmove commented
Thanks

2022-10-19 10:11 UTC, Sticknmove reviewed
Thanks

2022-10-19 10:11 UTC, Sticknmove reviewed
Thanks

2022-10-19 10:11 UTC, Sticknmove reviewed
Thanks

2022-10-19 10:12 UTC, Sticknmove reviewed
Thanks

2022-10-19 10:12 UTC, Sticknmove reviewed
Thanks

2022-10-19 10:12 UTC, Sticknmove reviewed
Thanks

2022-10-19 10:12 UTC, Sticknmove reviewed
Thanks

2022-10-19 10:13 UTC, Sticknmove reviewed
Thanks

2022-10-19 20:45 UTC, Sticknmove reviewed
Thanks