Improve spanish translation
microsoft/Web-Dev-For-Beginners pull request #829
Opened 2022-10-09 11:29 UTC by flamadev

- Correct spelling mistakes
- Fix markdown style
- Change technical terms where applicable

2022-10-09 11:30 UTC, flamadev commented
@microsoft-github-policy-service agree

2022-10-28 19:35 UTC, saragibby commented
@abrilurena as you have time, could you review this translation PR? Thank you!

2022-10-28 20:33 UTC, abrilurena requested changes
¡Hola, @flamadev ! Muchas gracias por tu ayuda y tiempo ❤️ hice algunos comentarios, si tienes alguna duda, por favor, no dudes en contactarme

2022-10-28 20:33 UTC, abrilurena commented on 1-getting-started-lessons/2-github-basics/translations/README.es.md
> +2. **Abre un PR**. A continuación, abre un PR. Para hacerlo, navega al repositorio bifurcado en GitHub. Verás una indicación en GitHub donde te preguntarán si deseas crear un nuevo PR. Haz clic allí
```suggestion
2. **Abre un Pull Request**. A continuación, abre un PR. Para hacerlo, navega al repositorio bifurcado en GitHub. Verás una indicación en GitHub donde te preguntarán si deseas crear un nuevo PR. Haz clic allí y te llevará a una interfaz donde puedes cambiar el título del mensaje de commit, asígnale una descripción más adecuada. Ahora, el mantenedor del repositorio que bifurcaste verá esta PR y _dedos cruzados_ valorarán y _fusionarán_ tu PR. Ahora eres un colaborador, ¡yay! :)
```

2022-10-28 20:33 UTC, abrilurena commented on 1-getting-started-lessons/2-github-basics/translations/README.es.md
> +3. **Limpiar**. Se considera una buena práctica _limpiar_ despuésde que tu PR fue combinada exitosamente. Limpia tanto tu rama local como la rama que enviaste a GitHub. Primero eliminémoslo localment
```suggestion
3. **Limpiar**. Se considera una buena práctica "_limpiar_" después de que tu Pull Request fue combinado a la rama principal exitosamente. Limpia tanto tu rama local como la rama que enviaste a GitHub. Primero eliminémoslo localmente con el siguiente comando:
```

2022-10-28 20:33 UTC, abrilurena commented on 1-getting-started-lessons/2-github-basics/translations/README.es.md
> +🚀 Desafío: Haz pareja con un amigo(a) para trabajar juntos en el código. Crea un proyecto de forma colaborativa, bifurca el código, crea ramas y combina los cambios.
```suggestion
🚀 Desafío: Haz pareja con un amigo(a) para trabajar juntos en el código. Crea un proyecto de forma colaborativa, haz fork del proyecto, crea ramas y combina los cambios.
```

creo que por lo regular escuchamos más "fork" que "bifurcar" pero no se que opinas :D 

```suggestion
🚀 Desafío: Haz pareja con un amigo(a) para trabajar juntos en el código. Crea un proyecto de forma colaborativa, haz fork del proyecto, crea ramas y combina los cambios.
```

2022-10-29 09:24 UTC, flamadev commented
> ¡Hola, @flamadev ! Muchas gracias por tu ayuda y tiempo ❤️ hice algunos comentarios, si tienes alguna duda, por favor, no dudes en contactarme

Gracias a ti! Me han parecido bien las sugerencias ❤️

2022-10-31 17:22 UTC, abrilurena approved these changes

2022-10-31 17:23 UTC, merged